name: pypi-publish

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: python3 setup.py sdist bdist_wheel
      - run: python3 -m pip install twine
      - run: python3 -m twine upload -u ${{ secrets.PYPI_USERNAME }} -p ${{ secrets.PYPI_PASSWORD }} --repository testpypi dist/*
      - run: python3 -m twine upload -u ${{ secrets.PYPI_USERNAME }} -p ${{ secrets.PYPI_PASSWORD }} --repository pypi dist/*
