name: pypi-publish

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
        python3 -m pip install setuptools wheel
        python3 setup.py sdist bdist_wheel
        python3 -m pip install twine
        ls
