name: pypi-publish

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: get-repository
      - uses: actions/checkout@v2
      - run: ls